<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Оформление заказа");

$request = $context->getRequest()->getQueryList()->toArray();

$APPLICATION->IncludeComponent(
    "bitrix:sale.order.ajax",
    strlen($request['ORDER_ID'] > 0) ? '' : 'simple',
    array(
        "PAY_FROM_ACCOUNT" => "N",
        "ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
        "COUNT_DELIVERY_TAX" => "N",
        "ALLOW_AUTO_REGISTER" => "Y",
        "SEND_NEW_USER_NOTIFY" => "Y",
        "DELIVERY_NO_AJAX" => "Y",
        "DELIVERY_NO_SESSION" => "N",
        "TEMPLATE_LOCATION" => ".default",
        "DELIVERY_TO_PAYSYSTEM" => "d2p",
        "USE_PREPAYMENT" => "N",
        "PROP_1" => "",
        "ALLOW_NEW_PROFILE" => "N",
        "SHOW_PAYMENT_SERVICES_NAMES" => "Y",
        "SHOW_STORES_IMAGES" => "N",
        "PATH_TO_BASKET" => "/personal/cart/",
        "PATH_TO_PERSONAL" => "/personal/",
        "PATH_TO_PAYMENT" => "/personal/order/payment/",
        "PATH_TO_AUTH" => "/auth/",
        "SET_TITLE" => "Y",
        "DISABLE_BASKET_REDIRECT" => "N",
        "PRODUCT_COLUMNS" => "",
        "PROP_2" => "",
        "COMPONENT_TEMPLATE" => ".default",
        "COMPATIBLE_MODE" => "Y",
        "PRODUCT_COLUMNS_VISIBLE" => array(
            0 => "PREVIEW_PICTURE",
            1 => "PROPS",
        ),
        "ADDITIONAL_PICT_PROP_7" => "-",
        "ADDITIONAL_PICT_PROP_8" => "-",
        "BASKET_IMAGES_SCALING" => "standard",
        "CODE_PHONES" => "",
        "ALLOW_APPEND_ORDER" => "Y",
        "SHOW_NOT_CALCULATED_DELIVERIES" => "L",
        "SPOT_LOCATION_BY_GEOIP" => "Y",
        "SHOW_VAT_PRICE" => "N",
        "USE_PRELOAD" => "Y",
        "ALLOW_USER_PROFILES" => "Y",
        "TEMPLATE_THEME" => "blue",
        "SHOW_ORDER_BUTTON" => "final_step",
        "SHOW_TOTAL_ORDER_BUTTON" => "N",
        "SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
        "SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
        "SHOW_DELIVERY_LIST_NAMES" => "Y",
        "SHOW_DELIVERY_INFO_NAME" => "Y",
        "SHOW_DELIVERY_PARENT_NAMES" => "Y",
        "SKIP_USELESS_BLOCK" => "Y",
        "BASKET_POSITION" => "after",
        "SHOW_BASKET_HEADERS" => "N",
        "DELIVERY_FADE_EXTRA_SERVICES" => "N",
        "SHOW_COUPONS_BASKET" => "N",
        "SHOW_COUPONS_DELIVERY" => "N",
        "SHOW_COUPONS_PAY_SYSTEM" => "N",
        "SHOW_NEAREST_PICKUP" => "N",
        "DELIVERIES_PER_PAGE" => "9",
        "PAY_SYSTEMS_PER_PAGE" => "9",
        "PICKUPS_PER_PAGE" => "5",
        "SHOW_PICKUP_MAP" => "Y",
        "SHOW_MAP_IN_PROPS" => "N",
        "PICKUP_MAP_TYPE" => "yandex",
        "PROPS_FADE_LIST_1" => array(
        ),
        "PROPS_FADE_LIST_2" => array(
        ),
        "USER_CONSENT" => "Y",
        "USER_CONSENT_ID" => "0",
        "USER_CONSENT_IS_CHECKED" => "N",
        "USER_CONSENT_IS_LOADED" => "N",
        "ACTION_VARIABLE" => "soa-action",
        "EMPTY_BASKET_HINT_PATH" => "/",
        "USE_PHONE_NORMALIZATION" => "Y",
        "SERVICES_IMAGES_SCALING" => "adaptive",
        "PRODUCT_COLUMNS_HIDDEN" => array(
        ),
        "HIDE_ORDER_DESCRIPTION" => "N",
        "USE_YM_GOALS" => "N",
        "USE_ENHANCED_ECOMMERCE" => "N",
        "USE_CUSTOM_MAIN_MESSAGES" => "N",
        "USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
        "USE_CUSTOM_ERROR_MESSAGES" => "N"
    ),
    false
);

require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");